default: &DEFAULT
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  database: septanow_dev
development:
  <<: *DEFAULT
  database: septanow_dev
test:
  <<: *DEFAULT
  database: septanow_test